### ISSUE TITLE
is there a reason why key type is fixed to "number"

### ISSUE THREAD

**Issue by kavaro** [Kirill486/functional-red-black-tree#9]
Thanks for making this Typescript version available.

I would like to use the tree with a custom key type (e.g. string) and a comparator function that compares custom keys.

Is there a way to achieve this ?

Thanks ...

**Comment by Kirill486** [comment]
Yes, there's a good way to do so.
It's called [**HashFunction**](https://en.wikipedia.org/wiki/Hash_function).

```
type hashFunction =  (valueType: ValueType) => number;

const hash = hashFunction(somethingIWantToStore);
tree.insert(hash, somethingIWantToStore);
```
[Here](http://www.cse.yorku.ca/~oz/hash.html) are a few hash functions for strings.

**Comment by kavaro** [comment]
A hash would for sure be a solution.

However with the javascript version the hash would not be required. 
By providing a custom compare function to the tree constructor one can use any datatype as key.
Unless I am missing something ...

**Comment by Kirill486** [comment]
#12 Created
